### ISSUE TITLE
[功能请求] 希望后续能支持歌词显示

### ISSUE THREAD

**Issue by OcrSu** [Zhoucheng133/net-player#2]
我试过很多客户端，但都没有 可移动歌词显示 的功能。
有的只是在应用内显示，不能独立成窗口自由拖动并置顶显示。

对了，元旦快乐！Net-Player是我用过的客户端里面，最美观 最好用的了，继续加油吧2024年！

这里是Navidrome 网页所提供的样式：
![image](https://github.com/Zhoucheng133/net-player/assets/75876201/45e2fa45-c431-4a77-bcb5-4fabdcb6a570)

**Comment by Zhoucheng133** [comment]
元旦快乐🎉 并且感谢你对本软件的肯定

很抱歉地告诉你，如果你和我一样通过Navidrome来使用netPlayer，虽然官方的API支持显示歌词，但是通过API获取的歌词无法实现其自动滚动（即带时间戳的歌词），详细见下图：  
![截屏2024-01-01 19 02 05](https://github.com/Zhoucheng133/net-player/assets/54197427/089ef410-db86-40e8-94e5-48d8b4900e43)

如果你看不懂没关系，简而言之就是可以实现获取歌词的功能，但是无法实现实时滚动歌词，所以你所找到的所有的客户端都不支持歌词滚动的功能也是理所当然的咯。  
如果我有时间我应该会添加上查看歌词的功能

**Comment by OcrSu** [comment]
> 元旦快乐🎉 并且感谢你对本软件的肯定
> 
> 很抱歉地告诉你，如果你和我一样通过Navidrome来使用netPlayer，虽然官方的API支持显示歌词，但是通过API获取的歌词无法实现其自动滚动（即带时间戳的歌词），详细见下图： ![截屏2024-01-01 19 02 05](https://private-user-images.githubusercontent.com/54197427/293581709-089ef410-db86-40e8-94e5-48d8b4900e43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDgwNjksIm5iZiI6MTcwNDEwNzc2OSwicGF0aCI6Ii81NDE5NzQyNy8yOTM1ODE3MDktMDg5ZWY0MTAtZGI4Ni00MGU4LTk0ZTUtNDhkOGI0OTAwZTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDExMTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNGRlMGU2MzE5NmNiOGJiZWJhNGI4M2VjNjU2NjZhZjJiNDIzNzMxMDRmZjgyZTlmMzk2ODRmN2EyMTE5NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oPw6pB8honfxBfr1iKDz9RIwtQzVLODwJZDGSOsS0yw)
> 
> 如果你看不懂没关系，简而言之就是可以实现获取歌词的功能，但是无法实现实时滚动歌词，所以你所找到的所有的客户端都不支持歌词滚动的功能也是理所当然的咯。 如果我有时间我应该会添加上查看歌词的功能



谢谢答复!

https://github.com/jeffvli/feishin
实际上我找到了一款可以实现滚动歌词的。（上面的开源项目）

但只能在应用内使用，而且滚动歌词到底后，当前歌词不能居中。
如下图，歌词已经到底：
![image](https://github.com/Zhoucheng133/net-player/assets/75876201/327ee147-3e63-411d-a07a-4def48c8193c)
理想位置如下：
![image](https://github.com/Zhoucheng133/net-player/assets/75876201/990b80d7-0ece-4a42-b1b0-f7c605398779)



我一开始想找这样一款客户端的目的是，
把Navidrome播放的音乐歌词显示到 OBS 内，这样直播音乐源可以通过Navidrome控制。
用本地播放器播放本地音乐 实现这个功能非常简单，但我确实不太想把音乐放在本地QWQ。

**Comment by OcrSu** [comment]
对了，它播放音乐是用的 mpv 播放器。

**Comment by Zhoucheng133** [comment]
我去看了一下你说的这个项目，这个项目使用的其实并不是Subsonic官方的歌词，而是使用了一个三方的API，地址为： 
`https://lrclib.net`
![截屏2024-01-01 23 17 55](https://github.com/Zhoucheng133/net-player/assets/54197427/a70fc10a-5daf-4db9-8c13-6faf40de3cb7)

之后有空我会尝试使用这个API来添加歌词功能，这可能会需要一些时间

**Comment by Zhoucheng133** [comment]
现在可以通过点击歌曲封面来显示歌词
详细效果见README中截图

**Comment by OcrSu** [comment]
> 现在可以通过点击歌曲封面来显示歌词 详细效果见README中截图

已经用上了，谢谢！

虽然这只是公共api，歌词对于大众需求来说已经够用了。
一些小众歌曲需要自己提交到api上。
我争取下午就把我歌单全部歌词同步上去！

PS:他这个歌词提交要求还挺高。
